### ISSUE TITLE
stime and etime does not respect HH:MM:SS format

### ISSUE THREAD

**Issue by Jacksoft** [fischpo/CUE-Sheet-Tracks#1]
If you have a cue image that is over 60 minutes stime and atime variable will be filled wrongly and the script stops with an error after 60:00 because ffmpeg expect a time format in HH:MM:SS type ("Invalid duration specification for ss").
For example if stime is 62:04 (MM:SS) it must be converted in 01:02:04 (HH:MM:SS) before ffmpeg command.

**Comment by fischpo** [comment]
Hi, thanks for bringing this to my attention. I tried to find any album cue which was more than an hour long but sadly couldn't find any. But I still have made some changes to accommodate this. I would appreciate it if you could test it on your end and report back if its working. Thanks!!

**Comment by Jacksoft** [comment]
Now it returns this error
>TRACK 74: [Yoshi's Cookie] [VS] BLIND
Traceback (most recent call last):
  File "C:\Users\Jacksoft\Desktop\Famicom\CUE.py", line 145, in <module>
    main()
  File "C:\Users\Jacksoft\Desktop\Famicom\CUE.py", line 116, in main
    stime,etime=atime[0].decode('utf-8').strip(),atime[1].decode('utf-8').strip()
                ~~~~~^^^
IndexError: list index out of range

This is the cuesheet section of track 74

>  TRACK 74 AUDIO
    TITLE "[Yoshi's Cookie] [VS] BLIND"
    PERFORMER "Nobuya, Akira, Tsutomu, Noriko"
    FLAGS DCP
    INDEX 00 69:40:32
    INDEX 01 69:41:32

Infos are from disc "[SCDC-00360] Famicom Sound History Series MARIO THE MUSIC"

**Comment by fischpo** [comment]
I have tried this with a few other albums and it seems to be working. I feel this might be caused by the cue file formatting so I tried finding the disc you mentioned but most of the sources are no longer available. Would you be able to share the cue sheet that you have?

**Comment by Jacksoft** [comment]
Here you go.

[cuefile.zip](https://github.com/fischpo/CUE-Sheet-Tracks/files/14827011/cuefile.zip)

**Comment by fischpo** [comment]
Right so as I thought the issue is that for some of the tracks in INDEX there is only one timestamp. This causes issues with other timestamps leading to the out of range error. I don't have a solution to deal with cue files that are in this format for now. 
So what you can do is remove those particular tracks which only have one timestamp from the cue. And later add those tracks in a proper format to a new cue file manually.
 It is a tedious method but sadly I don't have any other solution.
 I tried it for the cue file you sent and it worked. These are the tracks that I removed
```
TRACK 01
TRACK 17
TRACK 45
TRACK 47
TRACK 48
TRACK 49
TRACK 52
TRACK 53
TRACK 62
TRACK 71 
```
and here is the file without those tracks
[cuefileupdated.zip](https://github.com/fischpo/CUE-Sheet-Tracks/files/14827238/cuefileupdated.zip)

**Comment by Jacksoft** [comment]
Oh! I didn't noticed that!
Thank you!
